"""
    define words liat
"""
words = ['BOARD',
         'HOME',
         'MONK',
         'LION',
         'DECK',
         'FALL',
         'FAITH',
         'CORN',
         'THICK',
         'LIST',
         'DANCE',
         'WASTE',
         'DAIRY',
         'WINE',
         'FEW',
         'TIRE',
         'TEXT',
         'AGILE',
         'CHILD',
         'WRECK',
         'WHITE',
         'CARVE',
         'RUMOR',
         'WIDTH',
         'PILE',
         'BAKE',
         'BALL',
         'VIDEO',
         'FLOOD',
         'PEACE',
         'COMPETE',
         'UNLAWFUL',
         'INVESTMENT',
         'PLASTIC',
         'SUSPICION',
         'COMPLEX',
         'INNOCENT',
         'LIMITED',
         'REPTILE',
         'EMOTION',
         'GRADUATE',
         'PUDDING',
         'ORDINARY',
         'COMBINE',
         'COMPOSER',
         'MINIMUM',
         'CONFIDENCE',
         'FEELING',
         'EFFECTIVE',
         'INDICATION',
         'ETERNAL',
         'DIAMOND',
         'EXPOSURE',
         'FIREFIGHTER',
         'SOFTWARE',
         'REGISTER',
         'APPLAUD',
         'RATIONAL',
         'ARGUMENT'
         ]

# easy_words = [
#     'board',
#     'home',
#     'monk',
#     'lion',
#     'deck',
#     'fall',
#     'faith',
#     'corn',
#     'thick',
#     'list',
#     'dance',
#     'waste',
#     'dairy',
#     'wine',
#     'few',
#     'tire',
#     'text',
#     'agile',
#     'child',
#     'wreck',
#     'white',
#     'carve',
#     'rumor',
#     'width',
#     'pile',
#     'bake',
#     'ball',
#     'video',
#     'flood',
#     'peace'
# ]

# hard_words = [
#     'compete',
#     'unlawful',
#     'investment',
#     'plastic',
#     'suspicion',
#     'complex',
#     'innocent',
#     'limited',
#     'reptile',
#     'emotion',
#     'graduate',
#     'pudding',
#     'ordinary',
#     'combine',
#     'composer',
#     'minimum',
#     'confidence',
#     'feeling',
#     'effective',
#     'indication',
#     'eternal',
#     'diamond',
#     'exposure',
#     'firefighter',
#     'software',
#     'register',
#     'applaud',
#     'replace',
#     'rational',
#     'argument'
# ]
